- name: Set Prompt
  ansible.builtin.shell: set-prompt ci-server

- name: Create runner directory
  ansible.builtin.file:
    path: /home/ec2-user/github-runner
    state: directory
  become_user: ec2-user

- name: Download Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz
    dest: /home/ec2-user/github-runner
    remote_src: yes
  become_user: ec2-user

- name: Install Dependencies
  ansible.builtin.shell: /home/ec2-user/github-runner/bin/installdependencies.sh

#- name: Start Runner
#  ansible.builtin.shell: ./svc.sh uninstall
#  args:
#    chdir: /home/ec2-user/github-runner


- name: Install Runner
  ansible.builtin.shell: ./config.sh --token {{secrets.GITHUB_RUNNER_TOKEN}}; ./config.sh --unattended --replace --url https://github.com/raju-b72 --token {{secrets.GITHUB_RUNNER_TOKEN}}
  args:
    chdir: /home/ec2-user/github-runner
  become_user: ec2-user

- name: Start Runner
  ansible.builtin.shell: ./svc.sh install; ./svc.sh start
  args:
    chdir: /home/ec2-user/github-runner
