- name: Set Name in Prompt
  ansible.builtin.shell: set-prompt vault

- name: Install YUM Repo file
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Start Vault
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: true